name: dis
on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: |
          echo "I'm doing my tests from:"
          echo $GITHUB_REF
          echo $GITHUB_SHA
