name: e2e-test
on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  e2e-test:
    if: contains(github.event.issue.labels.*.name, 'e2e-test/auto')
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm doing my tests"
