name: e2e
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'Comment ID of the dispatching slash command'
        required: false
      pr-number:
        description: 'Pull request number of the dispatching slash command'
        required: false
      pr-merge-sha:
        description: 'Merge commit SHA of the pull request of the dispatching slash command'
        required: false

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Workflow Dispatch Inputs
        run: |
          echo "Workflow Dispatch Inputs:"
          echo "  Comment ID: ${{ github.event.inputs.comment-id }}"
          echo "  PR Number: ${{ github.event.inputs.pr-number }}"
          echo "  PR Merge SHA: ${{ github.event.inputs.pr-merge-sha }}"
      - name: Print Git Branch and Commit
        run: |
          echo "Git Branch and Commit:"
          echo "  Branch: ${{ github.ref }}"
          echo "  Commit: ${{ github.sha }}"
      - name: Print GitHub context
        run: |
          echo "GitHub Context:"
          echo "  Event Name: ${{ github.event_name }}"
          echo "  Event Path: ${{ github.event_path }}"
          echo "  Event Payload: ${{ toJson(github.event) }}"
          echo "  Repository: ${{ github.repository }}"
          echo "  Pull Request: ${{ github.event.pull_request }}"
