name: e2e
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'Comment ID of the dispatching slash command'
        required: false
      pr-number:
        description: 'Pull request number to post check results to'
        required: false

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Print Git Branch and Commit
        run: |
          echo "Git Branch and Commit:"
          echo "  Branch: ${{ github.ref }}"
          echo "  Commit: ${{ github.sha }}"
      - name: Print GitHub context
        run: |
          echo "GitHub Context:"
          echo "  Event Name: ${{ github.event_name }}"
          echo "  Event Path: ${{ github.event_path }}"
          echo "  Event Payload: ${{ toJson(github.event) }}"
          echo "  Repository: ${{ github.repository }}"
          echo "  Pull Request: ${{ github.event.pull_request }}"
