name: e2e
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'Comment ID of the dispatching slash command'
        required: false

defaults:
  run:
    shell: bash

jobs:
  job:
    env:
      GITHUB_TOKEN: ${{ secrets.SYSUSER_GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status
        id: commit-status-init
        run: |
          printf 'JOB_START_TIME=%(%s)T\n' >> "$GITHUB_OUTPUT"
          gh api repos/${{ github.repository }}/statuses/${{ github.ref }} \
            -X POST \
            -f state="pending" \
            -f description="In progress - This check has started..." \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f context="${{ github.workflow }} / ${{ github.job }}"
      - uses: actions/checkout@v4
      - name: Print Workflow Dispatch Inputs
        run: |
          echo "Workflow Dispatch Inputs:"
          echo "  Comment ID: ${{ inputs.comment-id }}"
      - name: Print Git Branch and Commit
        run: |
          echo "Git Branch and Commit:"
          echo "  Branch: ${{ github.ref }}"
          echo "  Commit: ${{ github.sha }}"
      - name: Print GitHub context
        run: |
          echo "GitHub Context:"
          echo "  Event Name: ${{ github.event_name }}"
          echo "  Event Path: ${{ github.event_path }}"
          echo "  Event Payload: ${{ toJson(github.event) }}"
          echo "  Repository: ${{ github.repository }}"
          echo "  Pull Request: ${{ github.event.pull_request }}"
      - run: sleep 45
      - name: Set commit status
        id: commit-status-final
        if: always()
        run: |
          JOB_DURATION=$((now - ${{ steps.commit-status-init.outputs.JOB_START_TIME }}))
          JOB_STATUS=${{ job.status }}
          COMMIT_STATUS=${{ job.status }}
          [ "$JOB_STATUS" == "cancelled" ] && COMMIT_STATUS="failure"
          gh api repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -X POST \
            -f state="$COMMIT_STATUS" \
            -f description="${JOB_STATUS^} after ${JOB_DURATION}" \
            -f target_url="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
            -f context="${{ github.workflow }} / ${{ github.job }}"
