name: e2e
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'Comment ID of the dispatching slash command'
        required: false
      pr-number:
        description: 'Pull request number to post check results to'
        required: false

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat README.md
      - name: Print GitHub context
        run: |
          echo "GitHub Context:"
          echo "  Event Name: ${{ github.event_name }}"
          echo "  Event Path: ${{ github.event_path }}"
          echo "  Event Payload: ${{ toJson(github.event) }}"
          echo "  Repository: ${{ github.repository }}"
          echo "  Pull Request: ${{ github.event.pull_request }}"
      - name: Create check run
        run: |
          PR_NUMBER=${{ github.event.inputs.pr-number }}
          CHECK_RUN_ID=$(gh api repos/${{ github.repository }}/pulls/$PR_NUMBER/check-runs -X POST -F name="e2e" -F head_sha="$(git rev-parse HEAD)" --jq .id)
          echo "Check run created with ID $CHECK_RUN_ID"
        env:
          GITHUB_TOKEN: ${{ secrets.SYSUSER_GITHUB_TOKEN }}
