name: e2e-test
on:
  pull_request:
    types:
      - labeled
      - reopened
      - synchronize
      - ready_for_review

defaults:
  run:
    shell: bash

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  e2e-test:
    if: github.event.label.name == 'e2e-test/auto'
    runs-on: ubuntu-latest
    steps:
      - run: echo "I'm doing my tests"
