name: e2e
on:
  workflow_dispatch:
    inputs:
      comment-id:
        description: 'Comment ID of the dispatching slash command'
        required: false
      pr-number:
        description: 'Pull request number to post check results to'
        required: false

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cat README.md
      - name: Dump the github context
        run: echo "${{ toJson(github) }}"
#      - name: Create check run
#        run: |
#          PR_NUMBER=${{ github.event.inputs.pr-number }}
#          echo "PR_NUMBER=$PR_NUMBER"
#          CHECK_RUN_ID=$(gh api repos/${{ github.repository }}/check-runs -X POST -F name="e2e" -F head_sha="$(git rev-parse HEAD)" --jq .id)
#          echo "Check run created with ID $CHECK_RUN_ID"
#        env:
#          GITHUB_TOKEN: ${{ secrets.SYSUSER_GITHUB_TOKEN }}
      - name: Create check run
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository }}/check-runs
          name: e2e
          head_sha: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
