name: execute
on:
#  issue_comment:
#    types:
#      - created
#  pull_request_review_comment:
#    types:
#      - created
#  pull_request_review:
#    types:
#      - submitted
#      - edited
  pull_request:
    types:
      - labeled

defaults:
  run:
    shell: bash

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
  deploy:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'bot/deploy'
    steps:
      - run: echo "I was triggered by the label bot/deploy"
      - uses: checkout@v4
      - run: git status
  approve:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'bot/approve'
    steps:
      - run: echo "I was triggered by the label bot/approve"
      - uses: checkout@v4
      - run: git status
#  authorize:
#    runs-on: ubuntu-latest
#    if: github.event.issue.pull_request
#    outputs:
#      AUTHORIZED: ${{ steps.authorize.outputs.AUTHORIZED }}
#    steps:
#      - name: Dump GitHub context
#        env:
#          GITHUB_CONTEXT: ${{ toJson(github) }}
#        run: echo "$GITHUB_CONTEXT"
#      - run: echo "PR number ${{ github.event.issue.number }}"
#      - id: authorize
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        run: |
#          echo "Comment author ${{ github.event.comment.user.login }}"
#          echo AUTHORIZED=$(gh api repos/${{ github.repository }}/collaborators/${{ github.event.comment.user.login }}/permission --jq .user.permissions.maintain) >> $GITHUB_OUTPUT
#      - if: steps.authorize.outputs.AUTHORIZED == 'false'
#        run: gh pr comment ${{ github.event.issue.number }} -b "Sorry, only maintainers are allowed to trigger the lab deploy."
#  lab-deploy:
#    needs: authorize
#    if: needs.authorize.outputs.AUTHORIZED == 'true'
#    uses: ./.github/workflows/lab-deploy.yml
#    with:
#      labInstance: ${{ github.event.issue.number }}
  
