name: lab-deploy
on:
  workflow_call:
    inputs:
      labInstance:
        type: string
        description: Lab instance number
        required: true

defaults:
  run:
    shell: bash

jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ inputs.labInstance }}/head
      - run: |
          git status
          git diff
      - run: echo "Creating lab instance ${{ inputs.labInstance }}"
