name: lab-setup
on:
  workflow_dispatch: # yamllint disable-line rule:empty-values
    inputs:
      labInstance:
        type: string
        description: Lab cluster instance. Most often a PR number.
        required: true

jobs:
  workload:
    uses: ./.github/workflows/workload.yml
    with:
      lab: true
      labInstance: ${{ inputs.labInstance }}
