name: pr-bot
on:
  pull_request:
    types:
      - opened
      - reopened
  issue_comment:
    types:
      - created

defaults:
  run:
    shell: bash

permissions:
  pull-requests: write

env:
  GITHUB_TOKEN: ${{ secrets.ADMIN_GITHUB_TOKEN }}

jobs:
  opened:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: e2e-test-hold
        run: |
          if [ gh pr view ${{ github.event.number }} --json labels --jq .labels[].name | grep e2e-test ]; then
            gh issue edit ${{ github.event.number }} --add-label "e2e-test/hold"
          fi
  comment:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - uses: actions/checkout@v4
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: e2e-test-label
        env:
          COMMENT_BODY: "${{ github.event.comment.body }}"
        run: |
          REGEX="\/e2e-test (hold|auto|skip)"
          if [[ ${COMMENT_BODY} =~ ${REGEX} ]]; then
            echo "Matched ${BASH_REMATCH[1]}"
            # gh issue edit ${{ github.event.issue.number }} --add-label "e2e-test/${BASH_REMATCH[1]}"
          fi
          #CMD=$(echo "${COMMENT_BODY}" | grep -Eo '/e2e-test ')

          #RECOGNIZED_COMMANDS=$(echo ${COMMENT_BODY} | grep -Eo '/deploy|/lgtm|/approve|/redeploy|/test|/retest')
          #if [[ -n ${RECOGNIZED_COMMANDS} ]]; then
          #  AUTHORIZED=$(gh api repos/${{ github.repository }}/collaborators/${{ github.event.comment.user.login }}/permission --jq .user.permissions.maintain)
          #  if [[ ${AUTHORIZED} == "true" ]]; then
          #    for c in ${RECOGNIZED_COMMANDS}; do
          #      gh issue edit ${{ github.event.issue.number }} --add-label "bot${c}"
          #    done
          #  else
          #    echo "Sorry, only maintainers are allowed to use slash commands."
          #  fi
          #fi

