name: Pull Request Print

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  print_context:
    runs-on: ubuntu-latest

    steps:
      - name: Print GitHub context
        run: |
          echo "GitHub Context:"
          echo "  Event Name: ${{ github.event_name }}"
          echo "  Event Path: ${{ github.event_path }}"
          echo "  Event Payload: ${{ toJson(github.event) }}"
          echo "  Repository: ${{ github.repository }}"
          echo "  Pull Request: ${{ github.event.pull_request }}"
