name: trigger
on:
  issue_comment:
    types:
      - created
      - edited

defaults:
  run:
    shell: bash

jobs:
  authorize:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    outputs:
      AUTHORIZED: ${{ steps.authorize.outputs.AUTHORIZED }}
    steps:
      - run: echo "PR number ${{ github.event.issue.number }}"
      - id: authorize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Comment author ${{ github.event.comment.user.login }}"
          echo AUTHORIZED=$(gh api repos/${{ github.repository }}/collaborators/${{ github.event.comment.user.login }}/permission --jq .user.permissions.maintain) >> $GITHUB_OUTPUT
      - if: steps.authorize.outputs.AUTHORIZED == 'false'
        run: gh pr comment ${{ github.event.issue.number }} -b "Sorry, only maintainers are allowed to trigger the lab deploy."
  lab-deploy:
    needs: authorize
    if: needs.authorize.outputs.AUTHORIZED == 'true'
    uses: ${{ github.repository }}/.github/workflows/lab-deploy.yml@refs/pull/${{ github.event.issue.number }}/head
    with:
      labInstance: ${{ github.event.issue.number }}
  
