name: trigger
on:
  issue_comment:
    types:
      - created
      - edited

defaults:
  run:
    shell: bash

jobs:
  authorize:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request
    steps:
      - run: echo "PR number ${{ github.event.issue.number }}"
      - run: |
          echo "Comment author ${{ github.event.comment.user.login }}"
          echo AUTHORIZED=$(gh api repos/${{ github.repository }}/collaborators/${{ github.event.comment.user.login }}/permission --jq .user.permissions.maintain) >> $GITHUB_ENV
        id: authorize
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.authorize.outputs.AUTHORIZED == 'true'
        run: echo "Authorized"
      - if: steps.authorize.outputs.AUTHORIZED == 'false'
        run: echo "Not authorized"
