name: vanilla
on:
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
     # - run: echo CONTENT="["environment":"${{ inputs.environment }}"]" >> $GITHUB_OUTPUT
      - id: init
        run: |
          # echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
          echo "matrix={\"include\":[{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
        #run: echo "CONTENT=$(jq -n -c '{"environment":["euwe-npr"]}')" >> $GITHUB_OUTPUT
      #  if: ${{ inputs.environment != '' }}
    outputs:
      matrix: ${{ steps.init.outputs.matrix }}
  job:
    needs: init
    runs-on: ubuntu-latest
    strategy:
#      fail-fast: false
      matrix: ${{ fromJSON(needs.init.outputs.matrix) }}
 #       include:
 #         - environment: euwe-npr
 #         - environment: use2-npr
#        environment:
#          - euwe-npr
#          - use2-npr
##        override:
#         - ${{ inputs.environment != '' }}
#        exclude:
#          - { environment: euwe-npr }
#          - { environment: use2-npr }
#        include:
#          - { environment: "${{ inputs.environment }}" }
#    environment: ${{ matrix.environment }}
    steps:
#      - uses: actions/checkout@v4
      - run: echo ${{ matrix.project }}
      - run: echo ${{ matrix.config }}
#      - run: echo ${{ matrix.environment }}
#      - run: echo ${{ vars.K8S_CLUSTER }}
