name: workload
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/workload.yml
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: If provided, the workflow deploys to this Github environment only.
        type: string
        default: ""
  workflow_call:
    inputs:
      environment:
        required: false
        description: If provided, the workflow deploys to this Github environment only.
        type: string
        default: ""

env:
  DEFAULT_ENVIRONMENTS: '["euwe-npr","use2-npr"]'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ inputs.environment }}
      - run: echo ${{ env.DEFAULT_ENVIRONMENTS }}
      - run: echo ${{ github.event_name }}
      - id: default
        if: inputs.environment == ''
        run: |
          echo "gonna use default"
          echo ${{ env.DEFAULT_ENVIRONMENTS }}
          echo environments=${{ env.DEFAULT_ENVIRONMENTS }} >> $GITHUB_OUTPUT
      - id: override
        if: ${{ inputs.environment != '' }}
        run: echo environments=["${{ inputs.environment }}"] >> $GITHUB_OUTPUT
    outputs:
      environments: ${{ toJson(steps.*.outputs.environments) }}
  echo:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.init.outputs.environments }}
  matrix:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.init.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ vars.K8S_CLUSTER }}
