name: workload
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environments:
        required: false
        type: string
        default: "['use2-npr','euwe-npr']"
jobs:
  echo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(inputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ vars.K8S_CLUSTER }}
