name: workload
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      e2e-test:
        required: true
        type: boolean
        default: false
      e2e-test-environment:
        required: false
        type: string
jobs:
  echo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - use2-npr
          - euwe-npr
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ vars.K8S_CLUSTER }}
      - run: echo ${{ inputs.e2e-test }}
      - run: echo ${{ inputs.e2e-test-environment }}
