name: workload
on:
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - use2-npr
          - euwe-npr
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
  deploy:
    needs: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - use2-npr
          - euwe-npr
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
  verify:
    needs: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment:
          - use2-npr
          - euwe-npr
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
