name: workload
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: false
        description: If provided, the workflow deploys to this Github environment only.
        type: string
        default: ''

env:
  DEFAULT_ENVIRONMENTS: "['euwe-npr', 'use2-npr']"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ github.event_name }}
      - id: default
        if: inputs.environment == ''
        run: echo environments=$(echo ${{ env.DEFAULT_ENVIRONMENTS }} jq -c .) >> $GITHUB_OUTPUT
      - id: override
        if: ${{ inputs.environment != '' }}
        run: echo environments="['${{ inputs.environment }}']" >> $GITHUB_OUTPUT
    outputs:
      environments: ${{ steps.*.outputs.environments }}
  echo:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJSON(needs.init.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ vars.K8S_CLUSTER }}
