name: workload
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/workload.yml
  workflow_dispatch:
    inputs:
      environment:
        required: false
        description: If provided, the workflow deploys to this Github environment only.
        type: string
        default: ""
  workflow_call:
    inputs:
      environment:
        required: false
        description: If provided, the workflow deploys to this Github environment only.
        type: string
        default: ""

env:
  DEFAULT_ENVIRONMENTS: '["euwe-npr","use2-npr"]'

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - id: default
        if: inputs.environment == ''
        run: echo "ENVIRONMENTS_JSON=$(jq -n -r '["euwe-npr","use2-npr"] | tostring')" >> $GITHUB_OUTPUT
      - id: override
        if: ${{ inputs.environment != '' }}
        run: echo ENVIRONMENTS_JSON=["${{ inputs.environment }}"] >> $GITHUB_OUTPUT
    outputs:
      environments-matrix: ${{ toJson(steps.*.outputs.ENVIRONMENTS_JSON) }}
  echo:
    needs: init
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.init.outputs.ENVIRONMENTS_JSON }}
  matrix:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: ${{ fromJson(needs.init.outputs.environments-matrix) }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ vars.K8S_CLUSTER }}
