name: workload
on:
  workflow_dispatch:
    inputs:
      lab:
        required: false
        default: false
        description: "This is a deployment to a lab cluster. Defaults to false."
        type: boolean
      labInstance:
        required: false
        description: "Lab cluster instance to deploy to. Required if lab is true."
        type: string
  workflow_call:
    inputs:
      lab:
        required: false
        default: false
        description: "This is a deployment to a lab cluster. Defaults to false."
        type: boolean
      labInstance:
        required: false
        description: "Lab cluster instance to deploy to. Required if lab is true."
        type: string
jobs:
#  init:
#    runs-on: ubuntu-latest
#    steps:
#      - id: override
#        if: ${{ inputs.environment != '' }}
#        run: echo ENVIRONMENTS_JSON=["${{ inputs.environment }}"] >> $GITHUB_OUTPUT
#    outputs:
#      matrix: ${{ toJson(steps.override.outputs.ENVIRONMENTS_JSON) }}
  gaga:
#    needs: init
    runs-on: ubuntu-latest
    environment: ${{ inputs.lab && format('mgmt-lab{0}', inputs.labInstance) || 'mgmt-cmn' }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "yes"
