name: workload
on:
  workflow_dispatch:
    inputs:
      lab:
        required: true
        type: boolean
        default: false
      labInstance:
        required: false
        type: number
jobs:
#  init:
#    runs-on: ubuntu-latest
#    steps:
#      - id: override
#        if: ${{ inputs.environment != '' }}
#        run: echo ENVIRONMENTS_JSON=["${{ inputs.environment }}"] >> $GITHUB_OUTPUT
#    outputs:
#      matrix: ${{ toJson(steps.override.outputs.ENVIRONMENTS_JSON) }}
  gaga:
#    needs: init
    runs-on: ubuntu-latest
    environment: ${{ inputs.lab && format('mgmt-lab${0}', inputs.labInstance) || 'mgmt-cmn' }}
    steps:
      - uses: actions/checkout@v4
      - run: echo "yes"
