name: workload
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        required: true
        description: If provided, the workflow deploys to this Github environment only.
        type: string

env:
  ENVIRONMENTS: "['euwe-npr', 'use2-npr']"

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - id: default
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo environments="${{ env.ENVIRONMENTS }}" >> $GITHUB_OUTPUT
      - id: override
        if: ${{ github.event_name == 'workflow_call' }}
        run: echo environments="['${{ inputs.environment }}']" >> $GITHUB_OUTPUT
    outputs:
      environments: ${{ toJSON(steps.*.outputs.environments) }}
  echo:
    needs: init
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ${{ fromJSON(needs.init.outputs.environments) }}
    environment: ${{ matrix.environment }}
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.environment }}
      - run: echo ${{ vars.K8S_CLUSTER }}
